# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a2139160539389143bdfdd022b0026f7beda07c03069541cdce3b08cb6306449f500086ef9e3e19b2bfe764c97d26969c107dab6117472f2466654a9b7cc544

test:
  secret_key_base: bcc8bec8990743e39bbce98e69e55147663903d7fc12035dbd784676b2d752b851dee8c159a0acc75d58318d474450a51f63b45d91ffd10ddd34d7d033fb60bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
